// <auto-generated />
namespace CarDealership.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateAspNetUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateAspNetUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202201110202589_updateAspNetUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
